apiVersion: apps/v1
kind: Deployment
metadata:
  name: vege-receipe-deployment
  labels:
    app: vege-receipe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vege-receipe
  template:
    metadata:
      labels:
        app: vege-receipe
    spec:
      containers:
      - name: vege-receipe
        image: dashrathpawara/vege-receipe:4
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"