apiVersion: apps/v1
kind: Deployment
metadata:
  name: vege-receipe-deployment
  labels:
    app: vege-receipe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vege-receipe
  template:
    metadata:
      labels:
        app: vege-receipe
    spec:
      containers:
      - name: vege-receipe
        image: dashrathpawara/vege-receipe:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "your_project.settings"
        - name: DATABASE_URL
          value: "your_database_url"
